### ISSUE TITLE
Status/Home screen

### ISSUE THREAD

**Issue by cbarkr** [cmpt469-su23-group3/PipBoy_Android#16]
# TODO
- [x] Health bar component (?)
- [x] Main status layout (consider using [`TableLayout`](https://developer.android.com/guide/topics/ui/layout/grid))
- [x] Bottom bar (stat summary)

# Reference
![Image](https://github.com/cmpt469-su23-group3/PipBoy_Android/assets/64287849/d067c7b8-9442-4851-9ea2-f7db05591839)

# Notes
- The image may be rendered like:
```xml
<ImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:src="@drawable/status"
    android:tintMode="multiply"
    app:tint="@color/text_1"
/>
```
