### ISSUE TITLE
NFC Holotape logic

### ISSUE THREAD

**Issue by cbarkr** [cmpt469-su23-group3/PipBoy_Android#20]
## TODO
- [x] Listener for NFC tag input
- [ ] For objects/layouts editable by a holotape, assign a UUID
- [ ] Make some inv items (chosen to be edited in last step) hidden -> `layout.setVisibility(View.GONE)`
- [ ] When scanning id from holotape, operate on the item with the associated UUID
    - [ ] Quests: marked as complete, colours change + toast
    - [ ] Items: make them visible again -> `layout.setVisibility(View.VISIBLE)`

## Resources
- [NFC basics | Android Developers](https://developer.android.com/guide/topics/connectivity/nfc/nfc)
